version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gosec
    - misspell
    - gocritic
    - revive
    - prealloc
    - unconvert
    - nolintlint

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        # Bubble Tea framework requires value receivers for Update/View/Init methods
        # Kubernetes types are also large by design
        - hugeParam
        # Don't enforce named results for all functions
        - unnamedResult
        # Allow single case switches for type assertions
        - singleCaseSwitch

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
          disabled: true  # Keep disabled for small project

    gosec:
      excludes:
        - G104

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports

output:
  show-stats: true
